// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8jkw5XdNH-C_LeiCeTRIXKaybQqQjXWw',
    appId: '1:116877629362:web:6d57796a46b9c08733f6ab',
    messagingSenderId: '116877629362',
    projectId: 'secret-santa-a5756',
    authDomain: 'secret-santa-a5756.firebaseapp.com',
    storageBucket: 'secret-santa-a5756.firebasestorage.app',
    measurementId: 'G-WVW5TJ4VBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgqlF5GS0KmFenelAXNo5Yqt2aVvjvoTY',
    appId: '1:116877629362:android:3ff2e098678e71c333f6ab',
    messagingSenderId: '116877629362',
    projectId: 'secret-santa-a5756',
    storageBucket: 'secret-santa-a5756.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSg0JJDNnjndhIxn7SSwXx1CJQfK-JKIM',
    appId: '1:116877629362:ios:8b686823f9b8eaeb33f6ab',
    messagingSenderId: '116877629362',
    projectId: 'secret-santa-a5756',
    storageBucket: 'secret-santa-a5756.firebasestorage.app',
    iosBundleId: 'com.example.secretSanta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSg0JJDNnjndhIxn7SSwXx1CJQfK-JKIM',
    appId: '1:116877629362:ios:8b686823f9b8eaeb33f6ab',
    messagingSenderId: '116877629362',
    projectId: 'secret-santa-a5756',
    storageBucket: 'secret-santa-a5756.firebasestorage.app',
    iosBundleId: 'com.example.secretSanta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8jkw5XdNH-C_LeiCeTRIXKaybQqQjXWw',
    appId: '1:116877629362:web:a27fdab1c306ba5f33f6ab',
    messagingSenderId: '116877629362',
    projectId: 'secret-santa-a5756',
    authDomain: 'secret-santa-a5756.firebaseapp.com',
    storageBucket: 'secret-santa-a5756.firebasestorage.app',
    measurementId: 'G-4K442MMF8R',
  );
}
